services:
  - type: static
    name: quizlens-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    headers:
      - source: "/*"
        headers:
          - key: Content-Security-Policy
            value: "default-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self'; img-src 'self'; connect-src 'self';"
